server: 
  port: 9527
 
spring: 
  application:
    name: springcloud-demo-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 

#自定义请求路径 
zuul: 
#  ignored-services: springcloud-demo-provider-dept  #忽略springcloud-demo-provider-dept服务
  prefix: /demo                                      #为所有映射添加前缀
  ignored-services: "*"                              #忽略所有的服务
  routes: 
    zuulPath:                                        #路由名,唯一标识即可
      serviceId: springcloud-demo-provider-dept      #让Zuul代理springcloud-demo-provider-dept
      path: /mydept/**                               #指定路径模式
 
info:
  app.name: app-zuul-gateway9527
  company.name: www.test.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

