server:
  port: 80
  
spring:
   application:
    name: springcloud-demo-consumer

eureka:
  client:
#    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-demo-80
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
